language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2

install:
    - composer install --no-interaction --prefer-dist

script:
    - php vendor/bin/phpstan analyse ./src ./tests --level max
    - php vendor/bin/phpcs --standard=PSR12 ./src ./tests
    - php vendor/bin/tester ./tests -p phpdbg --coverage ./coverage.xml --coverage-src ./src

after_script:
    # Report Code Coverage
    - >
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config .coveralls.yml